---
# Handle errors using blocks
# Usage: ansible-playbook handle_errors.yml
- name: Handle errors
  hosts: managed_node_1
  gather_facts: false
  tasks:
    - name: Handle an error
      block:
        - name: Run a task that passes
          ansible.builtin.debug:
            msg: "I passed!"

        - name: Run a tasks that fails
          ansible.builtin.fail:
            msg: "I failed."

        - name: Try an unreachable task
          ansible.builtin.debug:
            msg: "I cannot be reached."
      rescue:
        - name: Show an error message
          ansible.builtin.debug:
            msg: "I run if a task in the block fails."
      always:
        - name: Run a task even if another task failed
          ansible.builtin.debug:
            msg: "I always run."
...
# code: language=ansible
# vi: set noai nu ts=2 sw=2 sts=2 sta et:
